# Generated by Django 4.0.6 on 2022-07-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='PhotoImage',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/%y/%m/%d'),
        ),
    ]
