# Generated by Django 4.0.6 on 2022-07-23 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscalias',
            fields=[
                ('FisID', models.AutoField(primary_key=True, serialize=False)),
                ('CodSiga', models.CharField(blank=True, max_length=10, null=True)),
                ('Nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('Distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('Especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('Tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('Situacion', models.CharField(blank=True, max_length=100, null=True)),
                ('Provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('Departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Correo', models.EmailField(blank=True, max_length=255, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('ConID', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(auto_now_add=True, null=True)),
                ('FisID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Fiscalias.fiscalias')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
