# Generated by Django 4.0.6 on 2022-07-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiscalias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalias',
            name='Departamento',
        ),
        migrations.AlterField(
            model_name='fiscalias',
            name='Telefono',
            field=models.TextField(blank=True, null=True),
        ),
    ]
