# Generated by Django 4.0.6 on 2022-07-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiscalias', '0002_remove_fiscalias_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalias',
            name='Departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
