# Generated by Django 4.0.6 on 2022-07-23 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fiscalias', '0003_fiscalias_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='FisID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fiscalias.fiscalias'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
