# Generated by Django 4.0.5 on 2022-07-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('idconsultas', models.IntegerField(db_column='idConsultas', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Fiscalia',
            fields=[
                ('idfiscalia', models.IntegerField(db_column='idFiscalia', primary_key=True, serialize=False)),
                ('fisdepartamento', models.CharField(blank=True, db_column='FisDepartamento', max_length=45, null=True)),
                ('fisprovincia', models.CharField(blank=True, db_column='FisProvincia', max_length=45, null=True)),
                ('fisdistrito', models.CharField(blank=True, db_column='FisDistrito', max_length=45, null=True)),
                ('fisnombre', models.CharField(blank=True, db_column='FisNombre', max_length=45, null=True)),
                ('fisespecialidad', models.CharField(blank=True, db_column='FisEspecialidad', max_length=45, null=True)),
                ('fistipo', models.CharField(blank=True, db_column='FisTipo', max_length=45, null=True)),
                ('fissituación', models.CharField(blank=True, db_column='FisSituación', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Fiscalia',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('constraseña', models.CharField(blank=True, db_column='Constraseña', max_length=45, null=True)),
                ('dirección', models.CharField(blank=True, db_column='Dirección', max_length=45, null=True)),
                ('usuariocol', models.CharField(blank=True, db_column='Usuariocol', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='FiscaliaDet',
            fields=[
                ('idfiscaliadet', models.OneToOneField(db_column='idFiscaliaDet', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fiscaliaApp.fiscalia')),
                ('fisdetcorreo', models.CharField(blank=True, db_column='FisDetCorreo', max_length=45, null=True)),
                ('fisdetdireccion', models.CharField(blank=True, db_column='FisDetDireccion', max_length=45, null=True)),
                ('fisdetencargado', models.CharField(blank=True, db_column='FisDetEncargado', max_length=45, null=True)),
                ('fiscalia_detcol', models.CharField(blank=True, db_column='Fiscalia_detcol', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Fiscalia_det',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idhistorial', models.IntegerField(db_column='idHistorial', primary_key=True, serialize=False)),
                ('idconsultas', models.ForeignKey(blank=True, db_column='Consultas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fiscaliaApp.consultas')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fiscaliaApp.usuario')),
            ],
            options={
                'db_table': 'Historial',
            },
        ),
        migrations.AddField(
            model_name='consultas',
            name='idfiscalia',
            field=models.ForeignKey(blank=True, db_column='idFiscalia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fiscaliaApp.fiscalia'),
        ),
        migrations.AddField(
            model_name='consultas',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fiscaliaApp.usuario'),
        ),
    ]
